# Generated by Django 4.1.2 on 2025-02-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiLSTM_CNN',
            fields=[
                ('LSTM_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Accuracy', models.TextField(max_length=100)),
                ('Precession', models.TextField(max_length=100)),
                ('F1_Score', models.TextField(max_length=100)),
                ('Recall', models.TextField(max_length=100)),
                ('Name', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'BiLSTM_CNN_algo',
            },
        ),
        migrations.DeleteModel(
            name='BILSTM',
        ),
    ]
